### ISSUE TITLE
prepare for new member

### ISSUE THREAD

**Issue by ztec-sannom** [ztec-sannom/hello-world#2]
# purpose  
note what I do for new member  

# tasks  
 - [ ] make summary about follow up rule
 - [ ] make GitHub repository for follow up
 - [ ] study about what I don't have the technology
